# Generated by Django 5.0.6 on 2026-06-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('BRANCH_MANAGER', 'Branch Manager')], default='BRANCH_MANAGER', max_length=20),
        ),
    ]
